CREATE OR REPLACE PROCEDURE TEST_EMP.PROCS.SP_LOAD_SAMPLE_DATA2("FULLY_QUALIFIED_SOURCE_TABLE" VARCHAR, "FULLY_QUALIFIED_TARGET_TABLE" VARCHAR) 
RETURNS VARCHAR 
LANGUAGE SQL 
EXECUTE AS CALLER 
AS

DECLARE 
cre_tbl_qry VARCHAR;
insrt_qry VARCHAR;

BEGIN

-- Create Target Table if it doesn't exists
CREATE TABLE IF NOT EXISTS IDENTIFIER(:FULLY_QUALIFIED_TARGET_TABLE) 
    AS SELECT * FROM IDENTIFIER(:FULLY_QUALIFIED_SOURCE_TABLE) WHERE 1=2;

-- Load the data
INSERT INTO IDENTIFIER(:FULLY_QUALIFIED_TARGET_TABLE) 
    SELECT * FROM IDENTIFIER(:FULLY_QUALIFIED_SOURCE_TABLE) SAMPLE (10);
	
RETURN 'Insertion of Sample Data completed';

END;

-- CALL TEST_EMP.PROCS.SP_LOAD_SAMPLE_DATA2('SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.CUSTOMER', 'TEST_EMP.HRDATA.CUSTOMER_TEST');
