There are three types of functions :-
	SYSTEM Defined Functions 
	User defined Functions 
	External Functions
System Defined Functions:-
	Scalar Functions:- Function it takes single row /Value as input and returns single value
	Agreegate Functions:- Function it takes multiple  rows/Values as input and returns single value
	Window Functions:- Subset of agreegate functions that can operate on subset of a rows.
	Table Functions:- Functions that are return in tabular format
	System Functions:- Functions that perform control operation or return system level information.
	
User Defined Functions:-
	SQL user defined functions:- SQL UDFs can be defined to return scalar value or tablar output
	Java script user defined functions: Java UDFs can be defined to return either scalar value or tabular output.

External Functions:-
    Snowflake supports external functions ,Which are stored and executed outside of snowflake(Aws and Azuere)
	
	
Scalar Functions:-
	Bitwise Expression Functions
	Conditional Expression Functions
	Context Functions
	Conversion Functions
	Data Generation Functions
	Date & Time Functions
	Encryption Functions
	Geospatial Functions
	Numeric Functions
	Semi-structured Data Functions
	String & Binary Functions
	String Functions (Regular Expressions)
	Utility & Hash Functions
	
Context Functions:-
	General context:-
		CURRENT_CLIENT
		CURRENT_DATE
		CURRENT_IP_ADDRESS
		CURRENT_REGION
		CURRENT_TIME
		CURRENT_TIMESTAMP
		CURRENT_VERSION
		GETDATE Alias for CURRENT_TIMESTAMP.
		LOCALTIME Alias for CURRENT_TIME.
		LOCALTIMESTAMP Alias for CURRENT_TIMESTAMP.
		SYSDATE
		SYSTIMESTAMP

	Session context:-
		ALL_USER_NAMES
		CURRENT_ACCOUNT Returns account locator.
		CURRENT_ACCOUNT_NAME Returns account name.
		CURRENT_ORGANIZATION_NAME
		CURRENT_ROLE
		CURRENT_AVAILABLE_ROLES
		CURRENT_SECONDARY_ROLES
		CURRENT_SESSION
		CURRENT_STATEMENT
		CURRENT_TRANSACTION
		CURRENT_USER
		GETVARIABLE
		LAST_QUERY_ID
		LAST_TRANSACTION

	Session object context:-
		CURRENT_DATABASE
		CURRENT_ROLE_TYPE
		CURRENT_SCHEMA
		CURRENT_SCHEMAS
		CURRENT_WAREHOUSE
		INVOKER_ROLE
		INVOKER_SHARE
		IS_DATABASE_ROLE_IN_SESSION
		IS_GRANTED_TO_INVOKER_ROLE
		IS_INSTANCE_ROLE_IN_SESSION
		IS_ROLE_IN_SESSION
		POLICY_CONTEXT

System Functions:-

	Control Functions 
		SYSTEM$ABORT_SESSION
		SYSTEM$ABORT_TRANSACTION
		SYSTEM$ADD_EVENT (for Snowflake Scripting)
		SYSTEM$AUTHORIZE_PRIVATELINK
		SYSTEM$AUTHORIZE_STAGE_PRIVATELINK_ACCESS
		SYSTEM$BLOCK_INTERNAL_STAGES_PUBLIC_ACCESS
		SYSTEM$CANCEL_ALL_QUERIES
		SYSTEM$CANCEL_QUERY
		SYSTEM$CLEANUP_DATABASE_ROLE_GRANTS
		SYSTEM$CONVERT_PIPES_SQS_TO_SNS
		SYSTEM$DISABLE_BEHAVIOR_CHANGE_BUNDLE
		SYSTEM$DISABLE_DATABASE_REPLICATION
		SYSTEM$ENABLE_BEHAVIOR_CHANGE_BUNDLE
		SYSTEM$FINISH_OAUTH_FLOW
		SYSTEM$GLOBAL_ACCOUNT_SET_PARAMETER
		SYSTEM$LINK_ACCOUNT_OBJECTS_BY_NAME
		SYSTEM$MIGRATE_SAML_IDP_REGISTRATION
		SYSTEM$PIPE_FORCE_RESUME
		SYSTEM$PIPE_REBINDING_WITH_NOTIFICATION_CHANNEL
		SYSTEM$REGISTER_CMK_INFO
		SYSTEM$REVOKE_PRIVATELINK
		SYSTEM$REVOKE_STAGE_PRIVATELINK_ACCESS
		SYSTEM$SET_EVENT_SHARING_ACCOUNT_FOR_REGION
		SYSTEM$SNOWPIPE_STREAMING_UPDATE_CHANNEL_OFFSET_TOKEN
		SYSTEM$START_OAUTH_FLOW
		SYSTEM$TASK_DEPENDENTS_ENABLE
		SYSTEM$UNBLOCK_INTERNAL_STAGES_PUBLIC_ACCESS
		SYSTEM$UNSET_EVENT_SHARING_ACCOUNT_FOR_REGION
		SYSTEM$USER_TASK_CANCEL_ONGOING_EXECUTIONS
		SYSTEM$WAIT
	Information Functions

		EXTRACT_SEMANTIC_CATEGORIES
		GET_ANACONDA_PACKAGES_REPODATA
		SHOW_PYTHON_PACKAGES_DEPENDENCIES
		SYSTEM$ALLOWLIST
		SYSTEM$ALLOWLIST_PRIVATELINK
		SYSTEM$BEHAVIOR_CHANGE_BUNDLE_STATUS
		SYSTEM$CLIENT_VERSION_INFO
		SYSTEM$CLUSTERING_DEPTH
		SYSTEM$CLUSTERING_INFORMATION
		SYSTEM$CLUSTERING_RATIO Deprecated; use the other clustering functions instead.
		SYSTEM$CURRENT_USER_TASK_NAME
		SYSTEM$DATABASE_REFRESH_HISTORY Deprecated; use DATABASE_REFRESH_HISTORY instead.
		SYSTEM$DATABASE_REFRESH_PROGRESS , SYSTEM$DATABASE_REFRESH_PROGRESS_BY_JOB 	Deprecated; use DATABASE_REFRESH_PROGRESS , DATABASE_REFRESH_PROGRESS_BY_JOB instead.
		SYSTEM$ESTIMATE_AUTOMATIC_CLUSTERING_COSTS
		SYSTEM$ESTIMATE_SEARCH_OPTIMIZATION_COSTS
		SYSTEM$EXTERNAL_TABLE_PIPE_STATUS
		SYSTEM$GENERATE_SAML_CSR
		SYSTEM$GENERATE_SCIM_ACCESS_TOKEN
		SYSTEM$GET_AWS_SNS_IAM_POLICY
		SYSTEM$GET_CLASSIFICATION_RESULT
		SYSTEM$GET_CMK_AKV_CONSENT_URL
		SYSTEM$GET_CMK_CONFIG
		SYSTEM$GET_CMK_INFO
		SYSTEM$GET_CMK_KMS_KEY_POLICY
		SYSTEM$GET_COMPUTE_POOL_STATUS
		SYSTEM$GET_DIRECTORY_TABLE_STATUS
		SYSTEM$GET_GCP_KMS_CMK_GRANT_ACCESS_CMD
		SYSTEM$GET_ICEBERG_TABLE_INFORMATION
		SYSTEM$GET_LOGIN_FAILURE_DETAILS
		SYSTEM$GET_PREDECESSOR_RETURN_VALUE
		SYSTEM$GET_PRIVATELINK
		SYSTEM$GET_PRIVATELINK_AUTHORIZED_ENDPOINTS
		SYSTEM$GET_PRIVATELINK_CONFIG
		SYSTEM$GET_SERVICE_LOGS
		SYSTEM$GET_SERVICE_STATUS
		SYSTEM$GET_SNOWFLAKE_PLATFORM_INFO
		SYSTEM$GET_TAG
		SYSTEM$GET_TAG_ALLOWED_VALUES
		SYSTEM$GET_TAG_ON_CURRENT_COLUMN
		SYSTEM$GET_TAG_ON_CURRENT_TABLE
		SYSTEM$GET_TASK_GRAPH_CONFIG
		SYSTEM$INTERNAL_STAGES_PUBLIC_ACCESS_STATUS
		SYSTEM$IS_APPLICATION_INSTALLED_FROM_SAME_ACCOUNT
		SYSTEM$IS_APPLICATION_SHARING_EVENTS_WITH_PROVIDER
		SYSTEM$IS_LISTING_PURCHASED
		SYSTEM$IS_LISTING_TRIAL
		SYSTEM$LAST_CHANGE_COMMIT_TIME
		SYSTEM$LOG, SYSTEM$LOG_<level> (for Snowflake Scripting)
		SYSTEM$PIPE_STATUS
		SYSTEM$QUERY_REFERENCE
		SYSTEM$REFERENCE
		SYSTEM$REGISTRY_LIST_IMAGES Deprecated; use the SHOW IMAGES IN IMAGE REPOSITORY command instead.
		SYSTEM$SET_RETURN_VALUE
		SYSTEM$SET_SPAN_ATTRIBUTES (for Snowflake Scripting)
		SYSTEM$SHOW_ACTIVE_BEHAVIOR_CHANGE_BUNDLES
		SYSTEM$SHOW_BUDGETS_IN_ACCOUNT
		SYSTEM$SHOW_EVENT_SHARING_ACCOUNTS
		SYSTEM$SHOW_OAUTH_CLIENT_SECRETS
		SYSTEM$STREAM_GET_TABLE_TIMESTAMP
		SYSTEM$STREAM_HAS_DATA
		SYSTEM$TASK_RUNTIME_INFO
		SYSTEM$TYPEOF
		SYSTEM$VALIDATE_STORAGE_INTEGRATION
		SYSTEM$VERIFY_CMK_INFO
		SYSTEM$VERIFY_EXTERNAL_OAUTH_TOKEN
		SYSTEM$WHITELIST Deprecated; use SYSTEM$ALLOWLIST instead.
		SYSTEM$WHITELIST_PRIVATELINK Deprecated; use SYSTEM$ALLOWLIST_PRIVATELINK instead.

	Query Information Functions:-
	 
		EXPLAIN_JSON
		GET_QUERY_OPERATOR_STATS
		SYSTEM$ESTIMATE_QUERY_ACCELERATION
		SYSTEM$EXPLAIN_PLAN_JSON
		SYSTEM$EXPLAIN_JSON_TO_TEXT
	